Now the rest
git-svn-id: http://www.netperf.org/svn/netperf4@170 44b83d64-6b03-0410-99c4-fe3b3a721505

diff --git a/branches/glib_migration/configure b/branches/glib_migration/configure
--- a/branches/glib_migration/configure
+++ b/branches/glib_migration/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 #endif"
 
 ac_config_libobj_dir=src/missing
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBOBJS PKG_CONFIG ac_pt_PKG_CONFIG WANT_DNS_TRUE WANT_DNS_FALSE WANT_DISK_TRUE WANT_DISK_FALSE NETSYS_SOURCE LIBOJBS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBOBJS PKG_CONFIG ac_pt_PKG_CONFIG WANT_DNS_TRUE WANT_DNS_FALSE WANT_DISK_TRUE WANT_DISK_FALSE WANT_VST_TRUE WANT_VST_FALSE NETSYS_SOURCE LIBOJBS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1042,6 +1042,7 @@ Optional Features:
   --enable-histogram      include individual op timing, may affect result
   --enable-dns            build the DNS performance test suite
   --enable-disk           build the DISK performance test suite
+  --enable-vst            build the VST performance test suite
   --enable-demo   emit interim results during the run. May affect results.
   --enable-unixdomain  include Unix Domain socket tests
   --enable-dlpi  include Unix Domain socket tests
@@ -3673,7 +3674,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3676 "configure"' > conftest.$ac_ext
+  echo '#line 3677 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5257,7 +5258,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5260:" \
+echo "$as_me:5261:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6318,11 +6319,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6321: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6322: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6325: \$? = $ac_status" >&5
+   echo "$as_me:6326: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6586,11 +6587,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6589: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6590: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6593: \$? = $ac_status" >&5
+   echo "$as_me:6594: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6690,11 +6691,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6693: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6694: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6697: \$? = $ac_status" >&5
+   echo "$as_me:6698: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9015,7 +9016,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9018 "configure"
+#line 9019 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9115,7 +9116,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9118 "configure"
+#line 9119 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11453,11 +11454,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11456: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11457: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11460: \$? = $ac_status" >&5
+   echo "$as_me:11461: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11557,11 +11558,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11560: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11561: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11564: \$? = $ac_status" >&5
+   echo "$as_me:11565: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13118,11 +13119,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13121: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13122: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13125: \$? = $ac_status" >&5
+   echo "$as_me:13126: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13222,11 +13223,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13225: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13226: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13229: \$? = $ac_status" >&5
+   echo "$as_me:13230: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15412,11 +15413,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15415: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15416: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15419: \$? = $ac_status" >&5
+   echo "$as_me:15420: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15680,11 +15681,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15683: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15684: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15687: \$? = $ac_status" >&5
+   echo "$as_me:15688: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15784,11 +15785,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15787: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15788: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15791: \$? = $ac_status" >&5
+   echo "$as_me:15792: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21658,6 +21659,7 @@ else
   WANT_DNS_FALSE=
 fi
 
+
 # see if we should be enabling dns support
 
 echo "$as_me:$LINENO: checking whether to include disk support" >&5
@@ -21704,6 +21706,55 @@ if test "$use_disk" = true; then
 else
   WANT_DISK_TRUE='#'
   WANT_DISK_FALSE=
+fi
+
+
+# see if we should be enabling vst support
+
+echo "$as_me:$LINENO: checking whether to include vst support" >&5
+echo $ECHO_N "checking whether to include vst support... $ECHO_C" >&6
+
+# Check whether --enable-vst or --disable-vst was given.
+if test "${enable_vst+set}" = set; then
+  enableval="$enable_vst"
+
+fi;
+
+case "$enable_vst" in
+	yes)
+		use_vst=true
+		;;
+	no)
+		use_vst=false
+		;;
+	'')
+		# whatever
+		use_vst=false
+		;;
+	*)
+		{ { echo "$as_me:$LINENO: error: --enable-vst takes yes or no" >&5
+echo "$as_me: error: --enable-vst takes yes or no" >&2;}
+   { (exit 1); exit 1; }; }
+		;;
+esac
+
+if $use_vst
+then
+	echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+	echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "$use_vst" = true; then
+  WANT_VST_TRUE=
+  WANT_VST_FALSE='#'
+else
+  WANT_VST_TRUE='#'
+  WANT_VST_FALSE=
 fi
 
 
@@ -23109,7 +23160,7 @@ esac
 
 
 # now spit it all out
-                                                                                ac_config_files="$ac_config_files Makefile include/Makefile src/Makefile doc/Makefile suites/Makefile suites/dns/Makefile suites/disk/Makefile netperf-config"
+                                                                                          ac_config_files="$ac_config_files Makefile include/Makefile src/Makefile doc/Makefile suites/Makefile suites/dns/Makefile suites/disk/Makefile suites/vst/Makefile netperf-config"
 
 
 cat >confcache <<\_ACEOF
@@ -23242,6 +23293,13 @@ if test -z "${WANT_DISK_TRUE}" && test -z "${WANT_DISK_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"WANT_DISK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"WANT_DISK\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${WANT_VST_TRUE}" && test -z "${WANT_VST_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"WANT_VST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"WANT_VST\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -23696,6 +23754,7 @@ do
   "suites/Makefile" ) CONFIG_FILES="$CONFIG_FILES suites/Makefile" ;;
   "suites/dns/Makefile" ) CONFIG_FILES="$CONFIG_FILES suites/dns/Makefile" ;;
   "suites/disk/Makefile" ) CONFIG_FILES="$CONFIG_FILES suites/disk/Makefile" ;;
+  "suites/vst/Makefile" ) CONFIG_FILES="$CONFIG_FILES suites/vst/Makefile" ;;
   "netperf-config" ) CONFIG_FILES="$CONFIG_FILES netperf-config" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
@@ -23857,6 +23916,8 @@ s,@WANT_DNS_TRUE@,$WANT_DNS_TRUE,;t t
 s,@WANT_DNS_FALSE@,$WANT_DNS_FALSE,;t t
 s,@WANT_DISK_TRUE@,$WANT_DISK_TRUE,;t t
 s,@WANT_DISK_FALSE@,$WANT_DISK_FALSE,;t t
+s,@WANT_VST_TRUE@,$WANT_VST_TRUE,;t t
+s,@WANT_VST_FALSE@,$WANT_VST_FALSE,;t t
 s,@NETSYS_SOURCE@,$NETSYS_SOURCE,;t t
 s,@LIBOJBS@,$LIBOJBS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
